"""
AI-Powered Cybersecurity Threat Monitoring Dashboard - Backend API
FastAPI service exposing threats, risk scores, alerts, and response actions.

Run:
    pip install -r requirements.txt
    uvicorn main:app --reload --port 8000

This is a PROTOTYPE: threat data is generated by data.py to simulate the
output of an AI/ML/NLP/computer-vision/behavioural-analytics detection
pipeline. Swap generate_threats()/generate_alerts() for real model
inference + a database in production.
"""
from datetime import datetime
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from models import (
    Threat, Alert, ActionRequest, ActionResponse, OverviewStats, RiskLevel,
    ThreatCategory, ThreatStatus,
)
from data import generate_threats, generate_alerts, generate_overview

app = FastAPI(
    title="Threat Monitoring API",
    description="AI-driven threat classification, risk scoring, and response orchestration API.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory "database" for the prototype
THREATS: List[Threat] = generate_threats(28)
ALERTS: List[Alert] = generate_alerts(THREATS, 9)


@app.get("/")
def root():
    return {"service": "Threat Monitoring API", "status": "online", "time": datetime.utcnow()}


@app.get("/api/overview", response_model=OverviewStats)
def get_overview():
    """Aggregated stats for the overview dashboard: counts by risk level, trend line, blocked actions."""
    return generate_overview(THREATS, ALERTS)


@app.get("/api/threats", response_model=List[Threat])
def get_threats(
    risk_level: Optional[RiskLevel] = None,
    category: Optional[ThreatCategory] = None,
    status: Optional[ThreatStatus] = None,
    search: Optional[str] = Query(None, description="Search by user, title, or threat ID"),
):
    """List threats for the threat table, with optional filters."""
    results = THREATS
    if risk_level:
        results = [t for t in results if t.risk_level == risk_level]
    if category:
        results = [t for t in results if t.category == category]
    if status:
        results = [t for t in results if t.status == status]
    if search:
        q = search.lower()
        results = [
            t for t in results
            if q in t.title.lower() or q in t.target_user.lower() or q in t.id.lower()
        ]
    return results


@app.get("/api/threats/{threat_id}", response_model=Threat)
def get_threat(threat_id: str):
    """Full detail + explainable evidence for a single threat (for a drill-down panel)."""
    for t in THREATS:
        if t.id == threat_id:
            return t
    raise HTTPException(status_code=404, detail="Threat not found")


@app.get("/api/alerts", response_model=List[Alert])
def get_alerts(unacknowledged_only: bool = False):
    """Alerts feed for the alerts panel."""
    if unacknowledged_only:
        return [a for a in ALERTS if not a.acknowledged]
    return ALERTS


@app.post("/api/alerts/{alert_id}/acknowledge", response_model=Alert)
def acknowledge_alert(alert_id: str):
    for a in ALERTS:
        if a.id == alert_id:
            a.acknowledged = True
            return a
    raise HTTPException(status_code=404, detail="Alert not found")


@app.post("/api/actions", response_model=ActionResponse)
def perform_action(req: ActionRequest):
    """
    Execute (simulate) a recommended response action against a threat:
    block link, quarantine email, revoke session, strengthen auth,
    alert admin, or escalate.
    """
    threat = next((t for t in THREATS if t.id == req.threat_id), None)
    if not threat:
        raise HTTPException(status_code=404, detail="Threat not found")

    if req.action not in threat.recommended_actions and req.action != "Continue monitoring":
        # still allow it, but note it wasn't the top recommendation
        pass

    if req.action.value in ("Block malicious link", "Quarantine email", "Revoke session"):
        threat.status = ThreatStatus.CONTAINED
    elif req.action.value == "Escalate incident":
        threat.status = ThreatStatus.INVESTIGATING

    return ActionResponse(
        success=True,
        threat_id=threat.id,
        action=req.action,
        message=f"{req.action.value} executed for {threat.id} ({threat.target_user}).",
        performed_at=datetime.utcnow(),
    )


@app.get("/api/risk-distribution")
def get_risk_distribution():
    """Counts per risk level, for the risk score cards / pie chart."""
    dist = {level.value: 0 for level in RiskLevel}
    for t in THREATS:
        dist[t.risk_level.value] += 1
    return dist
